name: doori_mobileapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.8+2

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  form_field_validator: ^1.1.0
  get:
  intl:
  flutter_screenutil:
  http:
  shared_preferences:
  loader_overlay: ^2.1.0
  image_picker: ^0.8.6+2

  loading_animation_widget:
  connectivity:
  wave: ^0.2.2
  percent_indicator: ^4.2.2
  fl_chart: ^0.60.0
  d_chart: ^2.2.4

  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  firebase_database: ^10.0.11
  firebase_crashlytics:
  fluttertoast: ^8.1.3

  flutter_blue_plus: ^1.32.1
  #flutter_blue_plus: 1.5.2
  location: ^4.4.0

  permission_handler: ^10.2.0
  webview_flutter: ^4.0.5
  #flutter_share:
  sqflite: ^2.2.5
  syncfusion_flutter_charts: ^20.4.54
  flutter_logs: ^2.1.10
  bluetooth_enable_fork: ^0.1.6
  collection:
  package_info_plus: ^3.1.0
  #background_fetch: ^1.1.5
  workmanager: ^0.5.1
  url_launcher: ^6.1.11
  flutter_local_notifications: ^9.5.1
  firebase_messaging:
  gif_view:
  gauge_indicator: ^0.4.3
  keep_screen_on: ^2.1.0
  easy_localization:
  get_storage:
  pdf:
  printing:
  google_fonts:
  path_provider:
  share_plus:
  # screenshot: ^2.0.0
  #For ios build version 1.3.0
  screenshot: ^1.3.0
  open_filex:
  shimmer:





dev_dependencies:
  flutter_test:
    sdk: flutter

  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.11.0

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/doori_logo.png"


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/locales/
    - assets/tips/
    - assets/images/heart/
    - assets/gif/
    - assets/images/login_background.png
    - assets/images/about_doori.png
    - assets/images/update_icon.png
    - assets/images/profile_details.png
    - assets/images/share_icon.png
    - assets/images/customer_support.png
    - assets/images/deactivate_account.png
    - assets/images/log_out.png
    - assets/images/tips.png
    - assets/images/back_button.png
    - assets/images/scanning.png
    - assets/images/bluebg.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
